{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dokudok-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dokudok-backend.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "dokudok-backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /management/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
